### ISSUE TITLE
Update needed for react 16

### ISSUE THREAD

**Issue by Pintouch** [gre/multi-slider#10]
I'm using MultiSlider on my project, I have those errors on the console : 
<img width="1440" alt="capture d ecran 2017-05-04 a 18 48 28" src="https://cloud.githubusercontent.com/assets/5173681/25715165/d6e99a72-30fa-11e7-9542-88379a327318.png">

Just to let you know.

**Comment by gre** [comment]
Would you like to provide a PR ?

**Comment by gre** [comment]
pushed a v4
