### ISSUE TITLE
Gradient as color of the line and circle customization

### ISSUE THREAD

**Issue by benonymus** [gre/multi-slider#13]
Hey, I really like your work, and would like to ask some,
Could I add a gradient such as linear-gradient(-90deg, #60ccae, #c6e152) to the colors to have it as the color of the line?
or maybe to add the gradient as a variable?
Also Is it possible to change the circles to for example a straight horizontal line?

Thank you

**Comment by gre** [comment]
no I don't think this is possible at the moment but you can definitely fork the library to make it possible.
plan is to be able to customize the rendering.

#6 #7 #8

**Comment by benonymus** [comment]
thank you
