### ISSUE TITLE
`onChange` only when user lifts handle

### ISSUE THREAD

**Issue by ShukantPal** [gre/multi-slider#15]
I want to implement a feature where the parent component's `onChange` callback is invoked only when the user lifts the mouse from the handle. This makes computationally expensive renders stop, when the user doesn't need them.

**Comment by nathanlogan** [comment]
@SukantPal, you could use [throttle](https://underscorejs.org/#throttle) or [debounce](https://underscorejs.org/#debounce) to accomplish that.

**Comment by ShukantPal** [comment]
Throttle and denounce are different things. This feature would've called onChange *only* when the user is done interacting with the slider, not after every 200ms for example.

**Comment by nathanlogan** [comment]
@SukantPal, right.  I was just talking about how to implement a version of what you were wanting to do (depending upon your specific requirements/context).
